development:
  adapter: sqlite3
  database: db/development.sqlite3
  host: localhost
  username: crowdcode
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: crowdcode_production
  pool: 5
  host: localhost
  username: ubuntu
  password: futuretrunks
  timeout: 5000
